#! /bin/zsh
#
# Recursively fetch MERMAID metadata (GeoCSV) from
# http://ds.iris.edu/data/reports/MH/ and save to ~/Downloads.
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 19-Aug-2022, Darwin Kernel Version 18.7.0

fetchdir=$MERMAID/iris/fetch/mda/

if [[ ! -d $fetchdir ]]; then
    mkdir -p $fetchdir
    printf "Made new directory: %s\n" $fetchdir

fi

cd $fetchdir
wget --recursive \
     --no-host-directories\
     --no-parent \
     --cut-dirs=3 \
     --reject="index.html*","*robots*" \
     http://ds.iris.edu/data/reports/MH/

rm robots.txt.tmp

printf "Wrote to %s\n" $fetchdir
