#! /bin/zsh
#
# Usage: mermaid2dmc <archive_date>
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 01-Dec-2021, Springdale Linux 7.4 (Verona)

# Parse input requested archive
archive=$1

# miniseed2dmc script location plus host and port
# (latter two assigned by IRIS and to be remain masked)
miniseed2dmc=/home/jdsimon/github/miniseed2dmc/miniseed2dmc # frisius
#miniseed2dmc=/Users/joelsimon/programs/miniseed2dmc/miniseed2dmc # mac
host=$MINISEED2DMC_HOST
port=$MINISEED2DMC_PORT

# Parent dir of float subdirs and log file
iris_dir=$MERMAID/iris/data/
station_dirs=$( ls -d1 $iris_dir/*/ )
mermaid2dmc_log=$iris_dir/mermaid2dmc.log
echo "<! BEGIN TRANSFER !>" >> $mermaid2dmc_log
echo "Archive: $archive" >> $mermaid2dmc_log

# Loop over every float sudbir and transmit mseeds; write state/syncfile locally
for station_dir in $( echo $station_dirs ); do
    station=$( basename $( echo $station_dir ))
    archive_dir=$iris_dir/$station/archive/$station:$archive/
    mseed_dir=$archive_dir/mseed/

    echo "\nAttempting to transmit: $mseed_dir"  >> $mermaid2dmc_log
    $miniseed2dmc $host:$port -p -v -w $archive_dir $mseed_dir >> $mermaid2dmc_log

done
echo "\n<! END TRANSFER !>\n" >> $mermaid2dmc_log
