#! /bin/zsh
#
# Create tarball of (only) GeoCSV files from most recent archive
#
# !!! ONLY WORKS ON MAC !!!
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 16-Feb-2024, Darwin Kernel Version 18.7.0

if [ "$OSTYPE"  = 'linux' ]; then
    echo "Only works on Mac"
    return 1

fi

cd $MERMAID/iris/data/
for float in P0*; do

    last_archive=$( ls $float/archive | tail -1 )
    last_archive_date=$( echo $last_archive | cut -c 7- )

    tar rvf ${last_archive_date}.tar $float/archive/$last_archive/meta/*geo_DET.csv

done
