#! /bin/zsh
#
# Create tarball of (only) GeoCSV files from most recent archive
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 02-Aug-2021, Darwin Kernel Version 18.7.0

cd $MERMAID/iris/data/
for float in P0*; do

    last_archive=$( ls $float/archive | tail -1 )
    last_archive_date=$( echo $last_archive | cut -c 7- )

    tar rvf ${last_archive_date}.tar $float/archive/$last_archive/meta/*geo_DET.csv

done
