#! /bin/zsh
#
# Create tarball of (only) GeoCSV files from most recent archive
#
# !!! ONLY WORKS ON MAC !!!
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 05-Jun-2025, Darwin Kernel Version 23.6.0

# Bizarre --
# $OSTYPE: in terminal returns "linux"
# $OSTYPE: in script returns "linux-gnu"
if [[ $OSTYPE =~ "linux" ]]; then
    echo "only works on Mac"
    return 1

fi

cd $MERMAID/iris/data/
station_list=$MERMAID/iris/scripts/station_list.txt
for float in $( tail -n +2 $station_list ); do
    last_archive=$( ls $float/archive | tail -1 )
    last_archive_date=$( echo $last_archive | cut -c 7- )
    tar rvf ${last_archive_date}.tar $float/archive/$last_archive/meta/*geo_DET_REQ.csv

done
