#! /bin/zsh
#
# Generate diff comparing mseed2sac metadata file in the second-to-last and most
# recent archive, and print lines that changed between old ('<') and new ('>').
#
# If nothing changed, and the file was only appended to, the only lines that are
# printed (beginning with '<') should be header/comment lines.
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 18-Aug-2022, Darwin Kernel Version 18.7.0

iris_dir=$MERMAID/iris/data/

for float_dir in $( ls -d $iris_dir*/ ) ; do

    cd $float_dir

    back2=$( ls -1 archive | tail -2 | head -1 )
    back1=$( ls -1 archive | tail -1 )

    back2_csv=archive/$back2/meta/${back2}-mseed2sac_metadata_DET.csv
    back1_csv=archive/$back1/meta/${back1}-mseed2sac_metadata_DET.csv

    bn_back2=$( basename $back2_csv )
    bn_back1=$( basename $back1_csv )

    diff_name=${bn_back2}_${bn_back1}.diff
    diff $back2_csv $back1_csv >! logs/$diff_name

    printf 'Lines in %s that changed in %s:\n' $bn_back2 $bn_back1
    grep --no-filename "<" logs/$diff_name
    printf '\n'

done
